<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NewsItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsItemRepository extends \Doctrine\ORM\EntityRepository {

    function findByPage($pageNumber, $newsPerPage) {
        $query = $this->createQueryBuilder('p')
                ->getQuery()
                ->setFirstResult($newsPerPage * ($pageNumber - 1))
                ->setMaxResults($newsPerPage);

        return new Paginator($query, $fetchJoinCollection = false);
    }

}
